steps:
- name: 'hashicorp/terraform'
  args: ['init', 'terraform']
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve', 'terraform']
  env:
    - 'TF_VAR_project=$PROJECT_ID'
    - 'TF_VAR_cluster=hello-world'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/httpd:$SHORT_SHA', '-f', './docker/Dockerfile', '.' ]
- name: "gcr.io/cloud-builders/docker"
  args: [ "push", "gcr.io/$PROJECT_ID/httpd:$SHORT_SHA" ]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
    - run
    - --filename=./k8s
    - --location=us-central1-c
    - --cluster=hello-world
    - --image=gcr.io/$PROJECT_ID/httpd:$SHORT_SHA