---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-world-service"
  namespace: "default"
  labels:
    app: "hello-world"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "hello-world"
  type: "LoadBalancer"